#!/usr/bin/env python3
# DESC: rewrite the frozen legacy component stylesheet under a scope class so
# the old and new house styles can render side by side on one page.
"""Prefix every selector in legacy/components.css with a scope class.

The gallery compares two versions of the same components. A toggle makes the
reader hold the previous state in memory; rendering both at once does not. That
needs the old stylesheet to stop being global, which is what this does.

Only plain selectors are rewritten. An at-rule prelude (@media, @supports) is
left alone and its body is scoped instead; a top-level :root / html selector
would be a token block, which the legacy sheet does not have — if one ever
appears, this refuses rather than silently producing wrong CSS.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SCOPE = ".gal-before"
HERE = Path(__file__).resolve().parent


def strip_comments(css: str) -> str:
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def scope_selector(sel: str, scope: str) -> str:
    parts = [p.strip() for p in sel.split(",") if p.strip()]
    out = []
    for p in parts:
        if p.startswith((":root", "html", "body")):
            raise SystemExit(
                f"refusing to scope a document-level selector: {p!r}\n"
                "the legacy sheet has grown a token block; scope it by hand"
            )
        out.append(f"{scope} {p}")
    return ",\n".join(out)


def scope_css(css: str, scope: str) -> str:
    """Flat stylesheets only — one level of `selector { decls }` and nothing else.

    An at-rule would need its body scoped rather than its prelude, so rather
    than half-handle it this refuses and asks for a hand.
    """
    css = strip_comments(css)
    if "@media" in css or "@supports" in css:
        raise SystemExit("legacy sheet now has at-rules; scope-legacy.py handles flat CSS only")

    blocks = re.findall(r"([^{}]+)\{([^{}]*)\}", css)
    if not blocks:
        raise SystemExit("no rules found — is the source really CSS?")

    out = []
    for sel, decls in blocks:
        decls = decls.strip()
        if not decls:
            continue
        body = "\n".join(f"  {line.strip()}" for line in decls.splitlines() if line.strip())
        out.append(f"{scope_selector(sel, scope)} {{\n{body}\n}}")
    return "\n\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", type=Path, default=HERE / "legacy" / "components.css")
    ap.add_argument("--out", type=Path, default=HERE / "legacy" / "components.scoped.css")
    ap.add_argument("--scope", default=SCOPE, help=f"scope selector (default {SCOPE})")
    args = ap.parse_args()

    if not args.src.is_file():
        print(f"no such file: {args.src}", file=sys.stderr)
        return 1

    body = scope_css(args.src.read_text(), args.scope)
    header = (
        f"/* Generated by scope-legacy.py from {args.src.name} — do not edit.\n"
        f"   Every selector is scoped under {args.scope} so the previous house\n"
        f"   style can render beside the current one. */\n\n"
    )
    args.out.write_text(header + body)
    print(f"wrote {args.out.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
